web/router.ex
defmodule Tally.Router do
  use Tally.Web, :router
  use Coherence.Router         # Add this

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session  # Add this
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true  # Add this
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", Tally do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/", Tally do
    pipe_through :browser # Use the default browser stack

    resources "/items", ItemController
  end

  scope "/", Tally do
    pipe_through :protected

    # add protected resources below
    resources "/login", PrivateController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Tally do
  #   pipe_through :api
  # end
end

lib/tally/endpoint.ex
defmodule Tally.Endpoint do
  use Phoenix.Endpoint, otp_app: :tally

  socket "/socket", Tally.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :tally, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_tally_key",
    signing_salt: "WhgtBP80"

  plug Tally.Router
end

lib/tally/repo.ex
defmodule Tally.Repo do
  use Ecto.Repo, otp_app: :tally
end

web/models/coherence/user.ex
defmodule Tally.User do
  use Tally.Web, :model
  use Coherence.Schema

  schema "users" do
    field :name, :string
    field :email, :string
    coherence_schema

    timestamps
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:name, :email] ++ coherence_fields)
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
    |> validate_coherence(params)
  end
end

web/models/item.ex
defmodule Tally.Item do
  use Tally.Web, :model


  schema "items" do
    field :name, :string
    field :serial, :string
    field :used_by, :string
    field :quantity, :string

    timestamps()
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:name, :serial, :used_by, :quantity])
    |> validate_required([:name, :serial, :used_by, :quantity])
  end

end

web/controllers/item_controller.ex
defmodule Tally.ItemController do
  use Tally.Web, :controller

  alias Tally.Item

  def index(conn, _params) do
    items = Repo.all(Item)
    render conn, "index.html", items: items
  end

  def show(conn, params) do

  end

  def new(conn, _params) do
    changeset = Item.changeset(%Item{}, %{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, params) do

  end

  def edit(conn, params) do

  end

  def update(conn, params) do

  end

  def delete(conn, params) do

  end

end

web/controllers/page_controller.ex
defmodule Tally.PageController do
  use Tally.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/coherence/coherence_view.ex
defmodule Coherence.CoherenceView do
  use Tally.Coherence.Web, :view
end

web/views/coherence/email_view.ex
defmodule Coherence.EmailView do
  use Tally.Coherence.Web, :view

end

web/views/coherence/invitation_view.ex
defmodule Coherence.InvitationView do
  use Tally.Coherence.Web, :view

end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use Tally.Coherence.Web, :view


end

web/views/coherence/password_view.ex
defmodule Coherence.PasswordView do
  use Tally.Coherence.Web, :view

end

web/views/coherence/registration_view.ex
defmodule Coherence.RegistrationView do
  use Tally.Coherence.Web, :view

end

web/views/coherence/session_view.ex
defmodule Coherence.SessionView do
  use Tally.Coherence.Web, :view


end

web/views/coherence/unlock_view.ex
defmodule Coherence.UnlockView do
  use Tally.Coherence.Web, :view


end

web/views/error_view.ex
defmodule Tally.ErrorView do
  use Tally.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/item_view.ex
defmodule Tally.ItemView do
  use Tally.Web, :view 
end

web/views/layout_view.ex
defmodule Tally.LayoutView do
  use Tally.Web, :view
end

web/views/page_view.ex
defmodule Tally.PageView do
  use Tally.Web, :view
end

web/templates/coherence/invitation/edit.html.eex
<br \>

<%= form_for @changeset, invitation_path(@conn, :create_user), fn f  -> %>

  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <input type="hidden" name="token" value="<%= @token %>">

  <div class="form-group">
    <%= required_label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control", required: "" %>
    <%= error_tag f, :name %>
  </div>

  <%= unless (login_field = Coherence.Config.login_field) == :email do %>
    <div class="form-group">
      <%= required_label f, login_field, class: "control-label" %>
      <%= text_input f, login_field, class: "form-control", required: "" %>
      <%= error_tag f, login_field %>
    </div>
  <% end %>

  <div class="form-group">
    <%= required_label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control", required: "" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= required_label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control", required: "" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= required_label f, :password_confirmation, class: "control-label" %>
    <%= password_input f, :password_confirmation, class: "form-control", required: "" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "Create", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>
<% end %>

web/templates/coherence/invitation/new.html.eex
<%= form_for @changeset, invitation_path(@conn, :create), [as: :invitation], fn f  -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <div class="form-group">
    <%= required_label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control", required: "" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= required_label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control", required: "" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit "Send Invitation", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
    <%= if invitation = @conn.assigns[:invitation] do %>
      <%= link "Resend Invitation!", to: invitation_path(@conn, :resend, invitation.id), class: "btn" %>
    <% end %>
  </div>
<% end %>

web/templates/coherence/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tally</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/coherence/layout/email.html.eex
<html>
  <head>
    <title><%= @email.subject %></title>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

web/templates/coherence/password/edit.html.eex
<br \>

<h3>Create a New Password</h3>

<%= form_for @changeset, password_path(@conn, :update, @changeset.data), [as: :password], fn f  -> %>

  <%= hidden_input f, :reset_password_token %>

  <div class="form-group">
    <%= required_label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control", required: "" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= required_label f, :password_confirmation, class: "control-label" %>
    <%= password_input f, :password_confirmation, class: "form-control", required: "" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "Update Password", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>
<% end %>

web/templates/coherence/password/new.html.eex
<br \>

<h3>Send reset password link</h3>

<%= form_for @changeset, password_path(@conn, :create), [as: :password], fn f  -> %>

  <div class="form-group">
    <%= required_label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control", required: "" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit "Reset Password", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>
<% end %>

web/templates/coherence/session/new.html.eex
<br \>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f  -> %>

  <% login_field = Coherence.Config.login_field %>
  <div class="form-group">
    <%= required_label f, login_field, class: "control-label" %>
    <%= text_input f, login_field, class: "form-control", required: "" %>
    <%= error_tag f, login_field %>
  </div>

  <div class="form-group">
    <%= required_label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control", required: "" %>
    <%= error_tag f, :password %>
  </div>

  <%= if @remember do %>
    <div class="form-group">
      <input type="checkbox"  name="remember"> Remember Me?
    </div>
    <br />
  <% end %>

  <div class="form-group">
    <%= submit "Sign In", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>

  <div class="form-group">
    <%= coherence_links(@conn, :new_session) %>
  </div>

<% end %>

web/templates/coherence/unlock/new.html.eex
<br \>

<%= form_for @conn, unlock_path(@conn, :create), [as: :unlock], fn f  -> %>

  <div class="form-group">
    <%= required_label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control", required: "" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= required_label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control", required: "" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Send Instructions", class: "btn btn-primary" %>
    <%= link "Cancel", to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>

<% end %>

web/templates/item/index.html.eex
<div class="top-component">
  <%= link to: item_path(@conn, :new), class: "right btn-floating btn-medium waves-effect waves-light orange" do %>
    <i class="material-icons">add</i></a>
  <% end %>
</div>


<div class="content">
  <table>
    <thead>
      <tr>
        <th>Item Name</th>
        <th>Serial #</th>
        <th>Used By</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>

    <%= for item <- @items do %>
    <tbody>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.serial %></td>
        <td><%= item.used_by %></td>
        <td><%= item.quantity %></td>
        <td></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

web/templates/item/new.html.eex
<h3>New Item</h3>
<div class="row">
  <div class="col s12">
    <%= form_for @changeset, item_path(@conn, :create), fn f -> %>
      <%= error_tag f, :name %>
      <%= text_input f, :name, placeholder: "Name of the Item", class: "form-control col s12" %>
      <%= text_input f, :serial, placeholder: "Serial Number", class: "form-control col s12" %>
      <%= text_input f, :used_by, placeholder: "Person that will use this item", class: "form-control col s10" %>
      <%= text_input f, :quantity, placeholder: "0", class: "form-control col s1 offset-s1" %>
      <%= submit "Create Item", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome to Tally!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>

    <header class="header">
      <nav class="orange">
        <div class="nav-wrapper container">
          <%= link "Tally", to: page_path(@conn, :index), class: "brand-logo" %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>Login</li>
          </ul>
        </div>
      </nav>
    </header>

    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>